package denial

import "time"

// SampleCases provides realistic clinical insurance denial scenarios for evaluation and demonstration.
var SampleCases = []DenialCase{
	{
		ID:                    "CASE-2026-AETNA-01",
		CreatedAt:             time.Now(),
		PatientName:           "Elena Rostova",
		PatientDOB:            "1994-06-14",
		PatientState:          "California",
		InsurerName:           "Aetna",
		PolicyID:              "AET-90412891",
		GroupNumber:           "GRP-TECH-5021",
		ClaimNumber:           "CLM-2026-88129",
		PlanType:              PlanTypeERISACommercial,
		ServiceDate:           "2026-08-10",
		DenialNoticeDate:      "2026-08-25",
		AppealDeadline:        "2027-02-21",
		TotalBilled:           4250.00,
		DeniedAmount:          3850.00,
		PatientResponsibility: 3850.00,
		Diagnoses: []Diagnosis{
			{Code: "G35", Description: "Multiple sclerosis, unspecified / Suspected central demyelinating disease", Primary: true},
			{Code: "H46.9", Description: "Unspecified optic neuritis", Primary: false},
			{Code: "R20.2", Description: "Paresthesia of skin / peripheral numbness", Primary: false},
		},
		Procedures: []Procedure{
			{Code: "70553", Description: "MRI brain with and without IV contrast", BilledUnits: 1, Charge: 3850.00},
			{Code: "99214", Description: "Office outpatient visit, established patient, 30-39 mins", BilledUnits: 1, Charge: 400.00},
		},
		DenialReason: DenialReason{
			CARCCode:      "CO-50",
			RARCCode:      "N130",
			Category:      "Medical Necessity / Clinical Policy Bulletin",
			RawLetterText: "Your plan's clinical guidelines (CPB 0268) require documented trial of 6 weeks of physical therapy or oral NSAIDs prior to authorization of brain magnetic resonance imaging. Service is considered not medically necessary.",
		},
		Physician: PhysicianInfo{
			Name:       "Dr. Sarah Lin",
			NPI:        "1942857102",
			Specialty:  "Neurology & Neuroimmunology",
			ClinicName: "UCSF Health Neurology Clinic",
			Phone:      "(415) 353-2273",
			Address:    "400 Parnassus Ave, San Francisco, CA 94143",
		},
		ClinicalSummary: "32-year-old female presents with acute monocular vision loss (optic neuritis) and ascending paresthesia in right upper and lower extremities. Emergency neurological exam demonstrates hyperreflexia and Lhermitte's sign. Immediate contrast MRI of the brain is urgently required to assess active periventricular and callosal demyelinating plaques under 2017 McDonald Diagnostic Criteria. Ordering physical therapy or NSAIDs for acute central demyelination is medically hazardous.",
		PriorConservativeTried: []string{
			"High-dose IV methylprednisolone pulse therapy in clinic",
			"Comprehensive autoimmune serum panel (ANA, ENA, Aquaporin-4)",
		},
	},
	{
		ID:                    "CASE-2026-UHC-02",
		CreatedAt:             time.Now(),
		PatientName:           "Robert M. Henderson",
		PatientDOB:            "1958-11-20",
		PatientState:          "Ohio",
		InsurerName:           "UnitedHealthcare",
		PolicyID:              "UHC-44918234",
		GroupNumber:           "GRP-AUTO-1092",
		ClaimNumber:           "CLM-2026-44019",
		PlanType:              PlanTypeMedicareAdv,
		ServiceDate:           "2026-07-15",
		DenialNoticeDate:      "2026-08-01",
		AppealDeadline:        "2026-10-30",
		TotalBilled:           48200.00,
		DeniedAmount:          42100.00,
		PatientResponsibility: 42100.00,
		Diagnoses: []Diagnosis{
			{Code: "I63.9", Description: "Cerebral infarction, unspecified (Ischemic Left MCA Stroke)", Primary: true},
			{Code: "G81.91", Description: "Hemiplegia, affecting right dominant side", Primary: false},
			{Code: "R47.01", Description: "Aphasia following cerebral infarction", Primary: false},
		},
		Procedures: []Procedure{
			{Code: "0120", Description: "Room and Board - Subacute Skilled Nursing Facility (SNF) Rehab", BilledUnits: 21, Charge: 31500.00},
			{Code: "97110", Description: "Physical therapy therapeutic exercises (15-min increments)", BilledUnits: 42, Charge: 6300.00},
			{Code: "97530", Description: "Occupational therapy functional activities / ADL retraining", BilledUnits: 28, Charge: 4300.00},
		},
		DenialReason: DenialReason{
			CARCCode:      "CO-50",
			RARCCode:      "M62",
			Category:      "Maximum Medical Improvement / Algorithmic Discharge",
			RawLetterText: "Review conducted under internal utilization criteria. The patient has reached a functional plateau and custodial level of care. Continued inpatient skilled rehabilitation is not medically necessary after day 14.",
		},
		Physician: PhysicianInfo{
			Name:       "Dr. Marcus Vance",
			NPI:        "1837209144",
			Specialty:  "Physical Medicine & Rehabilitation (PM&R)",
			ClinicName: "Cleveland Clinic Rehabilitation Hospital",
			Phone:      "(216) 444-2200",
			Address:    "9500 Euclid Ave, Cleveland, OH 44195",
		},
		ClinicalSummary: "67-year-old male post-left middle cerebral artery acute ischemic stroke. Inpatient therapy logs over the past 7 days establish objective functional progress: gait distance increased from 15 feet to 85 feet with platform walker; Berg Balance Score improved from 18/56 to 32/56. Patient has NOT plateaued. Discharging to custodial care guarantees contractures, immobility, and high aspiration/fall risk. Discharge cutoff was algorithmically triggered by Optum nH Predict without clinical exam.",
		PriorConservativeTried: []string{
			"Acute inpatient medical stabilization",
			"Bedside dysphagia therapy with modified barium swallow",
		},
	},
	{
		ID:                    "CASE-2026-CIGNA-03",
		CreatedAt:             time.Now(),
		PatientName:           "Devon Cole",
		PatientDOB:            "2001-03-29",
		PatientState:          "New York",
		InsurerName:           "Cigna",
		PolicyID:              "CIG-77192083",
		GroupNumber:           "GRP-MEDIA-4411",
		ClaimNumber:           "CLM-2026-11928",
		PlanType:              PlanTypeERISACommercial,
		ServiceDate:           "2026-08-05",
		DenialNoticeDate:      "2026-08-18",
		AppealDeadline:        "2027-02-14",
		TotalBilled:           19800.00,
		DeniedAmount:          18400.00,
		PatientResponsibility: 18400.00,
		Diagnoses: []Diagnosis{
			{Code: "K50.90", Description: "Crohn's disease, unspecified, without complications", Primary: true},
			{Code: "K52.9", Description: "Noninfective gastroenteritis and colitis, unspecified", Primary: false},
		},
		Procedures: []Procedure{
			{Code: "J1745", Description: "Injection, infliximab, excludes biosimilar, 10 mg", BilledUnits: 40, Charge: 17200.00},
			{Code: "96413", Description: "Chemotherapy / biologic intravenous infusion, first hour", BilledUnits: 1, Charge: 1200.00},
		},
		DenialReason: DenialReason{
			CARCCode:      "CO-197",
			RARCCode:      "N130",
			Category:      "Step Therapy / Formulary Exclusion",
			RawLetterText: "Precertification denied. Plan requires trial and failure of 2 oral immunomodulators (including 6 months of azathioprine or 6-mercaptopurine) before biologic infusion can be authorized.",
		},
		Physician: PhysicianInfo{
			Name:       "Dr. Elena Vasquez",
			NPI:        "1294817203",
			Specialty:  "Gastroenterology",
			ClinicName: "Mount Sinai Hospital Center for IBD",
			Phone:      "(212) 241-6500",
			Address:    "1 Gustave L. Levy Pl, New York, NY 10029",
		},
		ClinicalSummary: "25-year-old with aggressive, penetrating Crohn's disease with severe deep mucosal ulcerations on colonoscopy. Patient previously tested positive for TPMT (thiopurine methyltransferase) deficiency, making azathioprine and 6-MP clinically contraindicated due to life-threatening bone marrow suppression and agranulocytosis. Mandating step-therapy with thiopurines is dangerous and directly exposes patient to toxicities while risking bowel perforation and emergency surgical resection.",
		PriorConservativeTried: []string{
			"High-dose Oral Prednisone taper (Steroid refractory)",
			"Mesalamine 4.8g daily (Failed to induce remission)",
			"TPMT genetic test documented deficiency (Contraindicates thiopurines)",
		},
	},
}
